/* Generated by Yosys 0.7 (git sha1 61f6811, i686-w64-mingw32.static-gcc 4.9.3 -Os) */

(* top =  1  *)
(* src = "Mux.v:2" *)
module mux(sel, reset, din_0, v_0, din_1, v_1, muxOut, v_out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  (* src = "Mux.v:5" *)
  input [3:0] din_0;
  (* src = "Mux.v:7" *)
  input [3:0] din_1;
  (* src = "Mux.v:9" *)
  output [3:0] muxOut;
  (* src = "Mux.v:4" *)
  input reset;
  (* src = "Mux.v:3" *)
  input sel;
  (* src = "Mux.v:6" *)
  input v_0;
  (* src = "Mux.v:8" *)
  input v_1;
  (* src = "Mux.v:10" *)
  output v_out;
  NOT _27_ (
    .A(v_0),
    .Y(_00_)
  );
  NOR _28_ (
    .A(sel),
    .B(_00_),
    .Y(_01_)
  );
  NAND _29_ (
    .A(sel),
    .B(v_1),
    .Y(_02_)
  );
  NOT _30_ (
    .A(_02_),
    .Y(_03_)
  );
  NOR _31_ (
    .A(_03_),
    .B(_01_),
    .Y(_04_)
  );
  NOR _32_ (
    .A(_04_),
    .B(reset),
    .Y(v_out)
  );
  NOT _33_ (
    .A(din_0[0]),
    .Y(_05_)
  );
  NOT _34_ (
    .A(sel),
    .Y(_06_)
  );
  NAND _35_ (
    .A(_06_),
    .B(v_0),
    .Y(_07_)
  );
  NOR _36_ (
    .A(_07_),
    .B(_05_),
    .Y(_08_)
  );
  NOT _37_ (
    .A(din_1[0]),
    .Y(_09_)
  );
  NOR _38_ (
    .A(_02_),
    .B(_09_),
    .Y(_10_)
  );
  NOR _39_ (
    .A(_10_),
    .B(_08_),
    .Y(_11_)
  );
  NOR _40_ (
    .A(_11_),
    .B(reset),
    .Y(muxOut[0])
  );
  NOT _41_ (
    .A(din_0[1]),
    .Y(_12_)
  );
  NOR _42_ (
    .A(_07_),
    .B(_12_),
    .Y(_13_)
  );
  NOT _43_ (
    .A(din_1[1]),
    .Y(_14_)
  );
  NOR _44_ (
    .A(_02_),
    .B(_14_),
    .Y(_15_)
  );
  NOR _45_ (
    .A(_15_),
    .B(_13_),
    .Y(_16_)
  );
  NOR _46_ (
    .A(_16_),
    .B(reset),
    .Y(muxOut[1])
  );
  NOT _47_ (
    .A(din_0[2]),
    .Y(_17_)
  );
  NOR _48_ (
    .A(_07_),
    .B(_17_),
    .Y(_18_)
  );
  NOT _49_ (
    .A(din_1[2]),
    .Y(_19_)
  );
  NOR _50_ (
    .A(_02_),
    .B(_19_),
    .Y(_20_)
  );
  NOR _51_ (
    .A(_20_),
    .B(_18_),
    .Y(_21_)
  );
  NOR _52_ (
    .A(_21_),
    .B(reset),
    .Y(muxOut[2])
  );
  NOT _53_ (
    .A(din_0[3]),
    .Y(_22_)
  );
  NOR _54_ (
    .A(_07_),
    .B(_22_),
    .Y(_23_)
  );
  NOT _55_ (
    .A(din_1[3]),
    .Y(_24_)
  );
  NOR _56_ (
    .A(_02_),
    .B(_24_),
    .Y(_25_)
  );
  NOR _57_ (
    .A(_25_),
    .B(_23_),
    .Y(_26_)
  );
  NOR _58_ (
    .A(_26_),
    .B(reset),
    .Y(muxOut[3])
  );
endmodule
