/* Generated by Yosys 0.7 (git sha1 61f6811, i686-w64-mingw32.static-gcc 4.9.3 -Os) */

(* top =  1  *)
(* src = "Mux.v:2" *)
module mux(sel, reset, din_0, v_0, din_1, v_1, muxOut, v_out);
  (* src = "Mux.v:13" *)
  wire [3:0] _00_;
  (* src = "Mux.v:13" *)
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  (* src = "Mux.v:5" *)
  input [3:0] din_0;
  (* src = "Mux.v:7" *)
  input [3:0] din_1;
  (* src = "Mux.v:9" *)
  output [3:0] muxOut;
  (* src = "Mux.v:4" *)
  input reset;
  (* src = "Mux.v:3" *)
  input sel;
  (* src = "Mux.v:6" *)
  input v_0;
  (* src = "Mux.v:8" *)
  input v_1;
  (* src = "Mux.v:10" *)
  output v_out;
  NAND _28_ (
    .A(sel),
    .B(v_1),
    .Y(_02_)
  );
  NOT _29_ (
    .A(sel),
    .Y(_03_)
  );
  NAND _30_ (
    .A(_03_),
    .B(v_0),
    .Y(_04_)
  );
  NAND _31_ (
    .A(_04_),
    .B(_02_),
    .Y(_01_)
  );
  NOR _32_ (
    .A(din_0[0]),
    .B(sel),
    .Y(_05_)
  );
  NOT _33_ (
    .A(reset),
    .Y(_10_)
  );
  NOT _34_ (
    .A(din_1[0]),
    .Y(_06_)
  );
  NAND _35_ (
    .A(_06_),
    .B(sel),
    .Y(_07_)
  );
  NAND _36_ (
    .A(_07_),
    .B(_10_),
    .Y(_08_)
  );
  NOR _37_ (
    .A(_08_),
    .B(_05_),
    .Y(_00_[0])
  );
  NOR _38_ (
    .A(din_0[1]),
    .B(sel),
    .Y(_11_)
  );
  NOT _39_ (
    .A(din_1[1]),
    .Y(_12_)
  );
  NAND _40_ (
    .A(_12_),
    .B(sel),
    .Y(_13_)
  );
  NAND _41_ (
    .A(_13_),
    .B(_10_),
    .Y(_14_)
  );
  NOR _42_ (
    .A(_14_),
    .B(_11_),
    .Y(_00_[1])
  );
  NOR _43_ (
    .A(din_0[2]),
    .B(sel),
    .Y(_15_)
  );
  NOT _44_ (
    .A(din_1[2]),
    .Y(_16_)
  );
  NAND _45_ (
    .A(_16_),
    .B(sel),
    .Y(_17_)
  );
  NAND _46_ (
    .A(_17_),
    .B(_10_),
    .Y(_18_)
  );
  NOR _47_ (
    .A(_18_),
    .B(_15_),
    .Y(_00_[2])
  );
  NOR _48_ (
    .A(din_0[3]),
    .B(sel),
    .Y(_19_)
  );
  NOT _49_ (
    .A(din_1[3]),
    .Y(_20_)
  );
  NAND _50_ (
    .A(_20_),
    .B(sel),
    .Y(_21_)
  );
  NAND _51_ (
    .A(_21_),
    .B(_10_),
    .Y(_22_)
  );
  NOR _52_ (
    .A(_22_),
    .B(_19_),
    .Y(_00_[3])
  );
  NOT _53_ (
    .A(v_1),
    .Y(_23_)
  );
  NOR _54_ (
    .A(_03_),
    .B(_23_),
    .Y(_24_)
  );
  NOT _55_ (
    .A(v_0),
    .Y(_25_)
  );
  NOR _56_ (
    .A(sel),
    .B(_25_),
    .Y(_26_)
  );
  NOR _57_ (
    .A(_26_),
    .B(_24_),
    .Y(_27_)
  );
  NAND _58_ (
    .A(_27_),
    .B(_10_),
    .Y(_09_)
  );
  \$_DLATCH_P_  _59_ (
    .D(_00_[0]),
    .E(_09_),
    .Q(muxOut[0])
  );
  \$_DLATCH_P_  _60_ (
    .D(_00_[1]),
    .E(_09_),
    .Q(muxOut[1])
  );
  \$_DLATCH_P_  _61_ (
    .D(_00_[2]),
    .E(_09_),
    .Q(muxOut[2])
  );
  \$_DLATCH_P_  _62_ (
    .D(_00_[3]),
    .E(_09_),
    .Q(muxOut[3])
  );
  \$_DLATCH_P_  _63_ (
    .D(_01_),
    .E(_10_),
    .Q(v_out)
  );
endmodule
