/* Generated by Yosys 0.7 (git sha1 61f6811, i686-w64-mingw32.static-gcc 4.9.3 -Os) */

(* top =  1  *)
(* src = "Mux.v:2" *)
module mux(sel, reset, din_0, din_1, muxOut);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  (* src = "Mux.v:5" *)
  input [3:0] din_0;
  (* src = "Mux.v:6" *)
  input [3:0] din_1;
  (* src = "Mux.v:7" *)
  output [3:0] muxOut;
  (* src = "Mux.v:4" *)
  input reset;
  (* src = "Mux.v:3" *)
  input sel;
  NOT _21_ (
    .A(din_1[0]),
    .Y(_00_)
  );
  NOT _22_ (
    .A(sel),
    .Y(_01_)
  );
  NOR _23_ (
    .A(_01_),
    .B(_00_),
    .Y(_02_)
  );
  NOT _24_ (
    .A(din_0[0]),
    .Y(_03_)
  );
  NOR _25_ (
    .A(sel),
    .B(_03_),
    .Y(_04_)
  );
  NOR _26_ (
    .A(_04_),
    .B(_02_),
    .Y(_05_)
  );
  NOR _27_ (
    .A(_05_),
    .B(reset),
    .Y(muxOut[0])
  );
  NOT _28_ (
    .A(din_1[1]),
    .Y(_06_)
  );
  NOR _29_ (
    .A(_06_),
    .B(_01_),
    .Y(_07_)
  );
  NOT _30_ (
    .A(din_0[1]),
    .Y(_08_)
  );
  NOR _31_ (
    .A(_08_),
    .B(sel),
    .Y(_09_)
  );
  NOR _32_ (
    .A(_09_),
    .B(_07_),
    .Y(_10_)
  );
  NOR _33_ (
    .A(_10_),
    .B(reset),
    .Y(muxOut[1])
  );
  NOT _34_ (
    .A(din_1[2]),
    .Y(_11_)
  );
  NOR _35_ (
    .A(_11_),
    .B(_01_),
    .Y(_12_)
  );
  NOT _36_ (
    .A(din_0[2]),
    .Y(_13_)
  );
  NOR _37_ (
    .A(_13_),
    .B(sel),
    .Y(_14_)
  );
  NOR _38_ (
    .A(_14_),
    .B(_12_),
    .Y(_15_)
  );
  NOR _39_ (
    .A(_15_),
    .B(reset),
    .Y(muxOut[2])
  );
  NOT _40_ (
    .A(din_1[3]),
    .Y(_16_)
  );
  NOR _41_ (
    .A(_16_),
    .B(_01_),
    .Y(_17_)
  );
  NOT _42_ (
    .A(din_0[3]),
    .Y(_18_)
  );
  NOR _43_ (
    .A(_18_),
    .B(sel),
    .Y(_19_)
  );
  NOR _44_ (
    .A(_19_),
    .B(_17_),
    .Y(_20_)
  );
  NOR _45_ (
    .A(_20_),
    .B(reset),
    .Y(muxOut[3])
  );
endmodule
